// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BG_BUTTON 0
#define UI_THEME_COLOR_TEXT_SWITCH 1
#define UI_THEME_COLOR_CONTAINER 2

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_BG_Button[1];
extern const ui_theme_variable_t _ui_theme_alpha_BG_Button[1];

extern const ui_theme_variable_t _ui_theme_color_Text_Switch[1];
extern const ui_theme_variable_t _ui_theme_alpha_Text_Switch[1];

extern const ui_theme_variable_t _ui_theme_color_Container[1];
extern const ui_theme_variable_t _ui_theme_alpha_Container[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
