// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_MainHeader;
void ui_event_USBC32Switch(lv_event_t * e);
lv_obj_t * ui_USBC32Switch;
lv_obj_t * ui_HeaderUSBC32;
lv_obj_t * ui_TextC32;
void ui_event_USBC1Switch(lv_event_t * e);
lv_obj_t * ui_USBC1Switch;
lv_obj_t * ui_HeaderUSBC1;
lv_obj_t * ui_TextC1;
void ui_event_USBASwitch(lv_event_t * e);
lv_obj_t * ui_USBASwitch;
lv_obj_t * ui_HeaderUSBA;
lv_obj_t * ui_TextA45;
lv_obj_t * ui_ImageWiFi;
lv_obj_t * ui_SysTempDock;
lv_obj_t * ui_TextSysTemp;
lv_obj_t * ui_SysTemp;
lv_obj_t * ui_USBA1;
lv_obj_t * ui_ImageUSBA1;
lv_obj_t * ui_VoltageUSBA1;
lv_obj_t * ui_USBA2;
lv_obj_t * ui_ImageUSBA2;
lv_obj_t * ui_VoltageUSBA2;
lv_obj_t * ui_USBC3;
lv_obj_t * ui_ImageC3;
lv_obj_t * ui_VoltageC3;
lv_obj_t * ui_CurrentC3;
lv_obj_t * ui_PowerC3;
lv_obj_t * ui_USBC2;
lv_obj_t * ui_ImageC2;
lv_obj_t * ui_ImageC2Fast;
lv_obj_t * ui_VoltageC2;
lv_obj_t * ui_CurrentC2;
lv_obj_t * ui_PowerC2;
lv_obj_t * ui_USBC1;
lv_obj_t * ui_ImageC1;
lv_obj_t * ui_ImageC1Fast;
lv_obj_t * ui_VoltageC1;
lv_obj_t * ui_CurrentC1;
lv_obj_t * ui_PowerC1;
lv_obj_t * ui_MainPower;
lv_obj_t * ui_TextVoltage;
lv_obj_t * ui_Voltage;
lv_obj_t * ui_TextCurrent;
lv_obj_t * ui_Current;
lv_obj_t * ui_TextPower;
lv_obj_t * ui_Power;
void ui_event_Weather(lv_event_t * e);
lv_obj_t * ui_Weather;
lv_obj_t * ui_TextWeather;
void ui_event_Setting(lv_event_t * e);
lv_obj_t * ui_Setting;
lv_obj_t * ui_TextSetting;
// CUSTOM VARIABLES

// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_SettingHeader;
lv_obj_t * ui_TextSettingHeader;
lv_obj_t * ui_FreeSpace;
lv_obj_t * ui_SettingDock;
void ui_event_WiFiWebPage(lv_event_t * e);
lv_obj_t * ui_WiFiWebPage;
lv_obj_t * ui_ImageWiFiWebPage;
lv_obj_t * ui_TextWiFiWebPage;
void ui_event_AdvancedSetting(lv_event_t * e);
lv_obj_t * ui_AdvancedSetting;
lv_obj_t * ui_ImageADCAdjust;
lv_obj_t * ui_TextADCAdjust;
lv_obj_t * ui_PanelFanSwitch;
lv_obj_t * ui_ImageFanSwitch;
lv_obj_t * ui_TextFanSwitch;
void ui_event_FanSwitch(lv_event_t * e);
lv_obj_t * ui_FanSwitch;
void ui_event_SliderBrightness(lv_event_t * e);
lv_obj_t * ui_SliderBrightness;
lv_obj_t * ui_ImageBrightness;
lv_obj_t * ui_Brightness;
void ui_event_RotationPlus(lv_event_t * e);
lv_obj_t * ui_RotationPlus;
lv_obj_t * ui_TextRotationPlus;
void ui_event_RotationMinus(lv_event_t * e);
lv_obj_t * ui_RotationMinus;
lv_obj_t * ui_TextRotationMinus;
void ui_event_Back(lv_event_t * e);
lv_obj_t * ui_Back;
lv_obj_t * ui_TextBack;
// CUSTOM VARIABLES

// SCREEN: ui_AdvancedSettingScreen
void ui_AdvancedSettingScreen_screen_init(void);
lv_obj_t * ui_AdvancedSettingScreen;
lv_obj_t * ui_AdvancedSettingHeader;
lv_obj_t * ui_TextAdvancedSetting;
lv_obj_t * ui_AdvancedSettingDock;
void ui_event_USBA1Adjust(lv_event_t * e);
lv_obj_t * ui_USBA1Adjust;
lv_obj_t * ui_ImageUSBA1ADC;
lv_obj_t * ui_TextUSBA1;
lv_obj_t * ui_VoltageUSBA1ADC;
void ui_event_USBA2Adjust(lv_event_t * e);
lv_obj_t * ui_USBA2Adjust;
lv_obj_t * ui_ImageUSBA2ADC;
lv_obj_t * ui_TextUSBA3;
lv_obj_t * ui_VoltageUSBA2ADC;
void ui_event_ThermometerAdjust(lv_event_t * e);
lv_obj_t * ui_ThermometerAdjust;
lv_obj_t * ui_ImageThermometer;
lv_obj_t * ui_SysTempAdjust;
lv_obj_t * ui_TextThermometer;
lv_obj_t * ui_ThermometerControlDock;
void ui_event_ThermometerControl(lv_event_t * e);
lv_obj_t * ui_ThermometerControl;
lv_obj_t * ui_ImageThermometer2;
void ui_event_SyncTimeAdjust(lv_event_t * e);
lv_obj_t * ui_SyncTimeAdjust;
lv_obj_t * ui_ImageSyncTimeAdjust;
lv_obj_t * ui_TextSyncTimeAdjust;
lv_obj_t * ui_TextSyncTimeSet;
lv_obj_t * ui_LEDControlDock;
void ui_event_LEDControl(lv_event_t * e);
lv_obj_t * ui_LEDControl;
lv_obj_t * ui_ImageLEDControl;
void ui_event_AdvancedSettingBack(lv_event_t * e);
lv_obj_t * ui_AdvancedSettingBack;
lv_obj_t * ui_TextADCBack;
// CUSTOM VARIABLES

// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
lv_obj_t * ui_WiFiScreen;
lv_obj_t * ui_WIFIHeader;
lv_obj_t * ui_TextWIFIHeader;
void ui_event_WIFIBack(lv_event_t * e);
lv_obj_t * ui_WIFIBack;
lv_obj_t * ui_TextWIFIBack;
lv_obj_t * ui_WIFISettingDock;
void ui_event_WIFIStart(lv_event_t * e);
lv_obj_t * ui_WIFIStart;
lv_obj_t * ui_TextWIFIStart;
void ui_event_WIFIReset(lv_event_t * e);
lv_obj_t * ui_WIFIReset;
lv_obj_t * ui_TextWIFIReset;
lv_obj_t * ui_WIFIStatus;
lv_obj_t * ui_TEXTSSID;
lv_obj_t * ui_SSID;
lv_obj_t * ui_TEXTIP;
lv_obj_t * ui_IPADDR;
lv_obj_t * ui_TEXTSYNCTIME;
lv_obj_t * ui_SYNCTIME;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherScreen
void ui_WeatherScreen_screen_init(void);
lv_obj_t * ui_WeatherScreen;
void ui_event_WeatherBack(lv_event_t * e);
lv_obj_t * ui_WeatherBack;
lv_obj_t * ui_TextWeatherBack;
void ui_event_WeatherSetting(lv_event_t * e);
lv_obj_t * ui_WeatherSetting;
lv_obj_t * ui_TextWeatherSetting;
lv_obj_t * ui_WeatherDock;
lv_obj_t * ui_ImageTemp;
lv_obj_t * ui_ImageHumi;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_WeatherPanel;
lv_obj_t * ui_WeatherICON;
lv_obj_t * ui_Week;
lv_obj_t * ui_WheatherCHN0Panel;
lv_obj_t * ui_WeatherCHN;
lv_obj_t * ui_TimeDock;
lv_obj_t * ui_TextWTime;
lv_obj_t * ui_WHour;
lv_obj_t * ui_WMinute;
lv_obj_t * ui_WSecond;
lv_obj_t * ui_PowerDock;
lv_obj_t * ui_TextWVoltage;
lv_obj_t * ui_TextWCurrent;
lv_obj_t * ui_TextPower1;
lv_obj_t * ui_WVoltage;
lv_obj_t * ui_WCurrent;
lv_obj_t * ui_WPower;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui_AdvancedSettingScreen_screen_init();
    ui_WiFiScreen_screen_init();
    ui_WeatherScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
