// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void USBC32PON(lv_event_t * e);
void USBC32POFF(lv_event_t * e);
void USBC1PON(lv_event_t * e);
void USBC1POFF(lv_event_t * e);
void USBA45ON(lv_event_t * e);
void USBA45OFF(lv_event_t * e);
void FanSwitchON(lv_event_t * e);
void FanSwitchOFF(lv_event_t * e);
void RotationPlus(lv_event_t * e);
void RotationMinus(lv_event_t * e);
void USBA1Adjust(lv_event_t * e);
void USBA2Adjust(lv_event_t * e);
void TempAdjust(lv_event_t * e);
void TempControlON(lv_event_t * e);
void TempControlOFF(lv_event_t * e);
void LEDControlON(lv_event_t * e);
void LEDControlOFF(lv_event_t * e);
void WIFIStart(lv_event_t * e);
void WIFIResrt(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
