// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_BG_Button[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_BG_Button[1] = {255};

const ui_theme_variable_t _ui_theme_color_Text_Switch[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Text_Switch[1] = {255};

const ui_theme_variable_t _ui_theme_color_Container[1] = {0x393939};
const ui_theme_variable_t _ui_theme_alpha_Container[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

