// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "../ui.h"

void ui_AdvancedSettingScreen_screen_init(void)
{
    ui_AdvancedSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AdvancedSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AdvancedSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_AdvancedSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_AdvancedSettingHeader = lv_obj_create(ui_AdvancedSettingScreen);
    lv_obj_remove_style_all(ui_AdvancedSettingHeader);
    lv_obj_set_width(ui_AdvancedSettingHeader, 236);
    lv_obj_set_height(ui_AdvancedSettingHeader, 32);
    lv_obj_set_x(ui_AdvancedSettingHeader, 0);
    lv_obj_set_y(ui_AdvancedSettingHeader, 2);
    lv_obj_set_align(ui_AdvancedSettingHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_AdvancedSettingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AdvancedSettingHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AdvancedSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_AdvancedSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextAdvancedSetting = lv_label_create(ui_AdvancedSettingHeader);
    lv_obj_set_width(ui_TextAdvancedSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAdvancedSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextAdvancedSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextAdvancedSetting, "系统高级设置");
    ui_object_set_themeable_style_property(ui_TextAdvancedSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextAdvancedSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextAdvancedSetting, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdvancedSettingDock = lv_obj_create(ui_AdvancedSettingScreen);
    lv_obj_remove_style_all(ui_AdvancedSettingDock);
    lv_obj_set_width(ui_AdvancedSettingDock, 236);
    lv_obj_set_height(ui_AdvancedSettingDock, 172);
    lv_obj_set_x(ui_AdvancedSettingDock, 0);
    lv_obj_set_y(ui_AdvancedSettingDock, 38);
    lv_obj_set_align(ui_AdvancedSettingDock, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_AdvancedSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AdvancedSettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AdvancedSettingDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_AdvancedSettingDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);
    lv_obj_set_style_pad_left(ui_AdvancedSettingDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AdvancedSettingDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AdvancedSettingDock, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AdvancedSettingDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USBA1Adjust = lv_slider_create(ui_AdvancedSettingDock);
    lv_slider_set_range(ui_USBA1Adjust, 850, 1250);
    lv_slider_set_value(ui_USBA1Adjust, 1085, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_USBA1Adjust) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_USBA1Adjust, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_USBA1Adjust, 228);
    lv_obj_set_height(ui_USBA1Adjust, 28);
    lv_obj_set_x(ui_USBA1Adjust, 0);
    lv_obj_set_y(ui_USBA1Adjust, 2);
    lv_obj_set_align(ui_USBA1Adjust, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_USBA1Adjust, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_USBA1Adjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_USBA1Adjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_color(ui_USBA1Adjust, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_USBA1Adjust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_USBA1Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_USBA1Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_USBA1Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_USBA1Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_USBA1Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_USBA1Adjust, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USBA1Adjust, lv_color_hex(0x00FF02), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USBA1Adjust, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_USBA1Adjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USBA1Adjust, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageUSBA1ADC = lv_img_create(ui_USBA1Adjust);
    lv_img_set_src(ui_ImageUSBA1ADC, &ui_img_2092987087);
    lv_obj_set_width(ui_ImageUSBA1ADC, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageUSBA1ADC, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageUSBA1ADC, 5);
    lv_obj_set_y(ui_ImageUSBA1ADC, 0);
    lv_obj_set_align(ui_ImageUSBA1ADC, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageUSBA1ADC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageUSBA1ADC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageUSBA1ADC, 230);

    ui_TextUSBA1 = lv_label_create(ui_USBA1Adjust);
    lv_obj_set_width(ui_TextUSBA1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextUSBA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextUSBA1, 40);
    lv_obj_set_y(ui_TextUSBA1, 0);
    lv_obj_set_align(ui_TextUSBA1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextUSBA1, "USBA1电压");
    ui_object_set_themeable_style_property(ui_TextUSBA1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextUSBA1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextUSBA1, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageUSBA1ADC = lv_label_create(ui_USBA1Adjust);
    lv_obj_set_width(ui_VoltageUSBA1ADC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageUSBA1ADC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltageUSBA1ADC, -10);
    lv_obj_set_y(ui_VoltageUSBA1ADC, 0);
    lv_obj_set_align(ui_VoltageUSBA1ADC, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VoltageUSBA1ADC, "00.00V");
    ui_object_set_themeable_style_property(ui_VoltageUSBA1ADC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_VoltageUSBA1ADC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_VoltageUSBA1ADC, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USBA2Adjust = lv_slider_create(ui_AdvancedSettingDock);
    lv_slider_set_range(ui_USBA2Adjust, 850, 1250);
    lv_slider_set_value(ui_USBA2Adjust, 1085, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_USBA2Adjust) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_USBA2Adjust, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_USBA2Adjust, 228);
    lv_obj_set_height(ui_USBA2Adjust, 28);
    lv_obj_set_x(ui_USBA2Adjust, 0);
    lv_obj_set_y(ui_USBA2Adjust, 35);
    lv_obj_set_align(ui_USBA2Adjust, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_USBA2Adjust, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_USBA2Adjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_USBA2Adjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_color(ui_USBA2Adjust, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_USBA2Adjust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_USBA2Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_USBA2Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_USBA2Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_USBA2Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_USBA2Adjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_USBA2Adjust, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USBA2Adjust, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USBA2Adjust, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_USBA2Adjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USBA2Adjust, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageUSBA2ADC = lv_img_create(ui_USBA2Adjust);
    lv_img_set_src(ui_ImageUSBA2ADC, &ui_img_2092987087);
    lv_obj_set_width(ui_ImageUSBA2ADC, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageUSBA2ADC, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageUSBA2ADC, 5);
    lv_obj_set_y(ui_ImageUSBA2ADC, 0);
    lv_obj_set_align(ui_ImageUSBA2ADC, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageUSBA2ADC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageUSBA2ADC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageUSBA2ADC, 230);

    ui_TextUSBA3 = lv_label_create(ui_USBA2Adjust);
    lv_obj_set_width(ui_TextUSBA3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextUSBA3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextUSBA3, 40);
    lv_obj_set_y(ui_TextUSBA3, 0);
    lv_obj_set_align(ui_TextUSBA3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextUSBA3, "USBA2电压");
    ui_object_set_themeable_style_property(ui_TextUSBA3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextUSBA3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextUSBA3, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageUSBA2ADC = lv_label_create(ui_USBA2Adjust);
    lv_obj_set_width(ui_VoltageUSBA2ADC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageUSBA2ADC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltageUSBA2ADC, -10);
    lv_obj_set_y(ui_VoltageUSBA2ADC, 0);
    lv_obj_set_align(ui_VoltageUSBA2ADC, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VoltageUSBA2ADC, "00.00V");
    ui_object_set_themeable_style_property(ui_VoltageUSBA2ADC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_VoltageUSBA2ADC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_VoltageUSBA2ADC, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometerAdjust = lv_slider_create(ui_AdvancedSettingDock);
    lv_slider_set_value(ui_ThermometerAdjust, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ThermometerAdjust) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ThermometerAdjust, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_ThermometerAdjust, 228);
    lv_obj_set_height(ui_ThermometerAdjust, 28);
    lv_obj_set_x(ui_ThermometerAdjust, 0);
    lv_obj_set_y(ui_ThermometerAdjust, 68);
    lv_obj_set_align(ui_ThermometerAdjust, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_ThermometerAdjust, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ThermometerAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_ThermometerAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_color(ui_ThermometerAdjust, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ThermometerAdjust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ThermometerAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThermometerAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThermometerAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThermometerAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThermometerAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ThermometerAdjust, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThermometerAdjust, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThermometerAdjust, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ThermometerAdjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThermometerAdjust, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageThermometer = lv_img_create(ui_ThermometerAdjust);
    lv_img_set_src(ui_ImageThermometer, &ui_img_f7_thermometer_png);
    lv_obj_set_width(ui_ImageThermometer, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageThermometer, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageThermometer, -6);
    lv_obj_set_y(ui_ImageThermometer, 0);
    lv_obj_set_align(ui_ImageThermometer, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageThermometer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageThermometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageThermometer, 120);

    ui_SysTempAdjust = lv_label_create(ui_ThermometerAdjust);
    lv_obj_set_width(ui_SysTempAdjust, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SysTempAdjust, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SysTempAdjust, -10);
    lv_obj_set_y(ui_SysTempAdjust, 0);
    lv_obj_set_align(ui_SysTempAdjust, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_SysTempAdjust, "00.00℃");
    ui_object_set_themeable_style_property(ui_SysTempAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_SysTempAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_SysTempAdjust, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextThermometer = lv_label_create(ui_ThermometerAdjust);
    lv_obj_set_width(ui_TextThermometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextThermometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextThermometer, 40);
    lv_obj_set_y(ui_TextThermometer, 0);
    lv_obj_set_align(ui_TextThermometer, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextThermometer, "系统温度");
    ui_object_set_themeable_style_property(ui_TextThermometer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextThermometer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextThermometer, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometerControlDock = lv_obj_create(ui_AdvancedSettingDock);
    lv_obj_set_width(ui_ThermometerControlDock, 112);
    lv_obj_set_height(ui_ThermometerControlDock, 32);
    lv_obj_set_x(ui_ThermometerControlDock, 4);
    lv_obj_set_y(ui_ThermometerControlDock, 32);
    lv_obj_set_align(ui_ThermometerControlDock, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ThermometerControlDock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ThermometerControlDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ThermometerControlDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_ThermometerControlDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_width(ui_ThermometerControlDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThermometerControl = lv_switch_create(ui_ThermometerControlDock);
    lv_obj_set_width(ui_ThermometerControl, 64);
    lv_obj_set_height(ui_ThermometerControl, 26);
    lv_obj_set_x(ui_ThermometerControl, 32);
    lv_obj_set_y(ui_ThermometerControl, 0);
    lv_obj_set_align(ui_ThermometerControl, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_ThermometerControl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ThermometerControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_ThermometerControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text_Switch);

    lv_obj_set_style_radius(ui_ThermometerControl, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ThermometerControl, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThermometerControl, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThermometerControl, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageThermometer2 = lv_img_create(ui_ThermometerControlDock);
    lv_img_set_src(ui_ImageThermometer2, &ui_img_f7_thermometer_png);
    lv_obj_set_width(ui_ImageThermometer2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageThermometer2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageThermometer2, -15);
    lv_obj_set_y(ui_ImageThermometer2, 0);
    lv_obj_set_align(ui_ImageThermometer2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageThermometer2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageThermometer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageThermometer2, 128);

    ui_SyncTimeAdjust = lv_slider_create(ui_AdvancedSettingDock);
    lv_slider_set_range(ui_SyncTimeAdjust, 1, 120);
    lv_slider_set_value(ui_SyncTimeAdjust, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SyncTimeAdjust) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SyncTimeAdjust, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SyncTimeAdjust, 228);
    lv_obj_set_height(ui_SyncTimeAdjust, 28);
    lv_obj_set_x(ui_SyncTimeAdjust, 0);
    lv_obj_set_y(ui_SyncTimeAdjust, 138);
    lv_obj_set_align(ui_SyncTimeAdjust, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_SyncTimeAdjust, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SyncTimeAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_SyncTimeAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_width(ui_SyncTimeAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SyncTimeAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SyncTimeAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SyncTimeAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SyncTimeAdjust, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SyncTimeAdjust, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SyncTimeAdjust, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_SyncTimeAdjust, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    lv_obj_set_style_bg_color(ui_SyncTimeAdjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SyncTimeAdjust, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageSyncTimeAdjust = lv_img_create(ui_SyncTimeAdjust);
    lv_img_set_src(ui_ImageSyncTimeAdjust, &ui_img_199350223);
    lv_obj_set_width(ui_ImageSyncTimeAdjust, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageSyncTimeAdjust, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageSyncTimeAdjust, 5);
    lv_obj_set_y(ui_ImageSyncTimeAdjust, 0);
    lv_obj_set_align(ui_ImageSyncTimeAdjust, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageSyncTimeAdjust, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSyncTimeAdjust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageSyncTimeAdjust, 200);

    ui_TextSyncTimeAdjust = lv_label_create(ui_SyncTimeAdjust);
    lv_obj_set_width(ui_TextSyncTimeAdjust, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSyncTimeAdjust, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSyncTimeAdjust, -10);
    lv_obj_set_y(ui_TextSyncTimeAdjust, 0);
    lv_obj_set_align(ui_TextSyncTimeAdjust, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextSyncTimeAdjust, "1小时");
    ui_object_set_themeable_style_property(ui_TextSyncTimeAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextSyncTimeAdjust, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextSyncTimeAdjust, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSyncTimeSet = lv_label_create(ui_SyncTimeAdjust);
    lv_obj_set_width(ui_TextSyncTimeSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSyncTimeSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSyncTimeSet, 40);
    lv_obj_set_y(ui_TextSyncTimeSet, 0);
    lv_obj_set_align(ui_TextSyncTimeSet, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextSyncTimeSet, "同步间隔");
    ui_object_set_themeable_style_property(ui_TextSyncTimeSet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextSyncTimeSet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextSyncTimeSet, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LEDControlDock = lv_obj_create(ui_AdvancedSettingDock);
    lv_obj_set_width(ui_LEDControlDock, 112);
    lv_obj_set_height(ui_LEDControlDock, 32);
    lv_obj_set_x(ui_LEDControlDock, 120);
    lv_obj_set_y(ui_LEDControlDock, 32);
    lv_obj_set_align(ui_LEDControlDock, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_LEDControlDock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LEDControlDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_LEDControlDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_LEDControlDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_width(ui_LEDControlDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LEDControl = lv_switch_create(ui_LEDControlDock);
    lv_obj_set_width(ui_LEDControl, 64);
    lv_obj_set_height(ui_LEDControl, 26);
    lv_obj_set_x(ui_LEDControl, 32);
    lv_obj_set_y(ui_LEDControl, 0);
    lv_obj_set_align(ui_LEDControl, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_LEDControl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_LEDControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_LEDControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text_Switch);

    lv_obj_set_style_radius(ui_LEDControl, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LEDControl, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LEDControl, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LEDControl, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageLEDControl = lv_img_create(ui_LEDControlDock);
    lv_img_set_src(ui_ImageLEDControl, &ui_img_2108985116);
    lv_obj_set_width(ui_ImageLEDControl, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageLEDControl, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageLEDControl, -10);
    lv_obj_set_y(ui_ImageLEDControl, 0);
    lv_obj_set_align(ui_ImageLEDControl, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageLEDControl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLEDControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AdvancedSettingBack = lv_btn_create(ui_AdvancedSettingScreen);
    lv_obj_set_width(ui_AdvancedSettingBack, 236);
    lv_obj_set_height(ui_AdvancedSettingBack, 22);
    lv_obj_set_x(ui_AdvancedSettingBack, 0);
    lv_obj_set_y(ui_AdvancedSettingBack, -4);
    lv_obj_set_align(ui_AdvancedSettingBack, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_AdvancedSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AdvancedSettingBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AdvancedSettingBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_AdvancedSettingBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextADCBack = lv_label_create(ui_AdvancedSettingBack);
    lv_obj_set_width(ui_TextADCBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextADCBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextADCBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextADCBack, "返回");
    ui_object_set_themeable_style_property(ui_TextADCBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextADCBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextADCBack, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_USBA1Adjust, ui_event_USBA1Adjust, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_USBA2Adjust, ui_event_USBA2Adjust, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ThermometerAdjust, ui_event_ThermometerAdjust, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ThermometerControl, ui_event_ThermometerControl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SyncTimeAdjust, ui_event_SyncTimeAdjust, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LEDControl, ui_event_LEDControl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AdvancedSettingBack, ui_event_AdvancedSettingBack, LV_EVENT_ALL, NULL);

}
