// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_SettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_SettingHeader = lv_obj_create(ui_SettingScreen);
    lv_obj_remove_style_all(ui_SettingHeader);
    lv_obj_set_width(ui_SettingHeader, 236);
    lv_obj_set_height(ui_SettingHeader, 32);
    lv_obj_set_x(ui_SettingHeader, 0);
    lv_obj_set_y(ui_SettingHeader, 2);
    lv_obj_set_align(ui_SettingHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SettingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_SettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextSettingHeader = lv_label_create(ui_SettingHeader);
    lv_obj_set_width(ui_TextSettingHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSettingHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSettingHeader, 10);
    lv_obj_set_y(ui_TextSettingHeader, 0);
    lv_obj_set_align(ui_TextSettingHeader, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextSettingHeader, "系统设置");
    ui_object_set_themeable_style_property(ui_TextSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextSettingHeader, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreeSpace = lv_label_create(ui_SettingHeader);
    lv_obj_set_width(ui_FreeSpace, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FreeSpace, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FreeSpace, -10);
    lv_obj_set_y(ui_FreeSpace, 0);
    lv_obj_set_align(ui_FreeSpace, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FreeSpace, "ROM:000Byte");
    ui_object_set_themeable_style_property(ui_FreeSpace, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_FreeSpace, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_FreeSpace, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingDock = lv_obj_create(ui_SettingScreen);
    lv_obj_remove_style_all(ui_SettingDock);
    lv_obj_set_width(ui_SettingDock, 236);
    lv_obj_set_height(ui_SettingDock, 172);
    lv_obj_set_x(ui_SettingDock, 0);
    lv_obj_set_y(ui_SettingDock, 38);
    lv_obj_set_align(ui_SettingDock, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SettingDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_SettingDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_WiFiWebPage = lv_btn_create(ui_SettingDock);
    lv_obj_set_width(ui_WiFiWebPage, 228);
    lv_obj_set_height(ui_WiFiWebPage, 28);
    lv_obj_set_x(ui_WiFiWebPage, 0);
    lv_obj_set_y(ui_WiFiWebPage, 4);
    lv_obj_set_align(ui_WiFiWebPage, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_WiFiWebPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiWebPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiWebPage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WiFiWebPage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_WiFiWebPage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_ImageWiFiWebPage = lv_img_create(ui_WiFiWebPage);
    lv_img_set_src(ui_ImageWiFiWebPage, &ui_img_593743026);
    lv_obj_set_width(ui_ImageWiFiWebPage, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageWiFiWebPage, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_ImageWiFiWebPage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageWiFiWebPage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWiFiWebPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextWiFiWebPage = lv_label_create(ui_WiFiWebPage);
    lv_obj_set_width(ui_TextWiFiWebPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWiFiWebPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextWiFiWebPage, 45);
    lv_obj_set_y(ui_TextWiFiWebPage, 0);
    lv_obj_set_align(ui_TextWiFiWebPage, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextWiFiWebPage, "无线配置界面");
    lv_obj_set_style_text_font(ui_TextWiFiWebPage, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdvancedSetting = lv_btn_create(ui_SettingDock);
    lv_obj_set_width(ui_AdvancedSetting, 228);
    lv_obj_set_height(ui_AdvancedSetting, 28);
    lv_obj_set_x(ui_AdvancedSetting, 0);
    lv_obj_set_y(ui_AdvancedSetting, 35);
    lv_obj_set_align(ui_AdvancedSetting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_AdvancedSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AdvancedSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AdvancedSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AdvancedSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_AdvancedSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_ImageADCAdjust = lv_img_create(ui_AdvancedSetting);
    lv_img_set_src(ui_ImageADCAdjust, &ui_img_155116563);
    lv_obj_set_width(ui_ImageADCAdjust, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageADCAdjust, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_ImageADCAdjust, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageADCAdjust, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageADCAdjust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextADCAdjust = lv_label_create(ui_AdvancedSetting);
    lv_obj_set_width(ui_TextADCAdjust, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextADCAdjust, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextADCAdjust, 45);
    lv_obj_set_y(ui_TextADCAdjust, 0);
    lv_obj_set_align(ui_TextADCAdjust, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextADCAdjust, "系统高级设置");
    lv_obj_set_style_text_font(ui_TextADCAdjust, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFanSwitch = lv_obj_create(ui_SettingDock);
    lv_obj_set_width(ui_PanelFanSwitch, 228);
    lv_obj_set_height(ui_PanelFanSwitch, 32);
    lv_obj_set_x(ui_PanelFanSwitch, 0);
    lv_obj_set_y(ui_PanelFanSwitch, 66);
    lv_obj_set_align(ui_PanelFanSwitch, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelFanSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFanSwitch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelFanSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_PanelFanSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_border_width(ui_PanelFanSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageFanSwitch = lv_img_create(ui_PanelFanSwitch);
    lv_img_set_src(ui_ImageFanSwitch, &ui_img_2103744591);
    lv_obj_set_width(ui_ImageFanSwitch, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageFanSwitch, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_ImageFanSwitch, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageFanSwitch, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageFanSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextFanSwitch = lv_label_create(ui_PanelFanSwitch);
    lv_obj_set_width(ui_TextFanSwitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextFanSwitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextFanSwitch, 45);
    lv_obj_set_y(ui_TextFanSwitch, 0);
    lv_obj_set_align(ui_TextFanSwitch, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextFanSwitch, "散热开关");
    lv_obj_set_style_text_font(ui_TextFanSwitch, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSwitch = lv_switch_create(ui_PanelFanSwitch);
    lv_obj_set_width(ui_FanSwitch, 64);
    lv_obj_set_height(ui_FanSwitch, 26);
    lv_obj_set_x(ui_FanSwitch, 148);
    lv_obj_set_y(ui_FanSwitch, 0);
    lv_obj_set_align(ui_FanSwitch, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text_Switch);

    lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanSwitch, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_SettingDock);
    lv_slider_set_range(ui_SliderBrightness, 10, 100);
    lv_slider_set_value(ui_SliderBrightness, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 224);
    lv_obj_set_height(ui_SliderBrightness, 28);
    lv_obj_set_x(ui_SliderBrightness, 0);
    lv_obj_set_y(ui_SliderBrightness, 66);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderBrightness, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_BG_Button);
    lv_obj_set_style_outline_width(ui_SliderBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBrightness, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageBrightness = lv_img_create(ui_SliderBrightness);
    lv_img_set_src(ui_ImageBrightness, &ui_img_763584403);
    lv_obj_set_width(ui_ImageBrightness, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageBrightness, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageBrightness, 17);
    lv_obj_set_y(ui_ImageBrightness, 0);
    lv_obj_set_align(ui_ImageBrightness, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBrightness, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageBrightness, 230);

    ui_Brightness = lv_label_create(ui_SliderBrightness);
    lv_obj_set_width(ui_Brightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brightness, -10);
    lv_obj_set_y(ui_Brightness, 0);
    lv_obj_set_align(ui_Brightness, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Brightness, "50%");
    ui_object_set_themeable_style_property(ui_Brightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_Brightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_Brightness, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RotationPlus = lv_btn_create(ui_SettingDock);
    lv_obj_set_width(ui_RotationPlus, 110);
    lv_obj_set_height(ui_RotationPlus, 28);
    lv_obj_set_x(ui_RotationPlus, -59);
    lv_obj_set_y(ui_RotationPlus, 103);
    lv_obj_set_align(ui_RotationPlus, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_RotationPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RotationPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RotationPlus, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_RotationPlus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_RotationPlus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_TextRotationPlus = lv_label_create(ui_RotationPlus);
    lv_obj_set_width(ui_TextRotationPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextRotationPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextRotationPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextRotationPlus, "屏幕+90°");
    lv_obj_set_style_text_font(ui_TextRotationPlus, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RotationMinus = lv_btn_create(ui_SettingDock);
    lv_obj_set_width(ui_RotationMinus, 110);
    lv_obj_set_height(ui_RotationMinus, 28);
    lv_obj_set_x(ui_RotationMinus, 59);
    lv_obj_set_y(ui_RotationMinus, 103);
    lv_obj_set_align(ui_RotationMinus, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_RotationMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RotationMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RotationMinus, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_RotationMinus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_RotationMinus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_TextRotationMinus = lv_label_create(ui_RotationMinus);
    lv_obj_set_width(ui_TextRotationMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextRotationMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextRotationMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextRotationMinus, "屏幕-90°");
    lv_obj_set_style_text_font(ui_TextRotationMinus, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back = lv_btn_create(ui_SettingScreen);
    lv_obj_set_width(ui_Back, 236);
    lv_obj_set_height(ui_Back, 22);
    lv_obj_set_x(ui_Back, 0);
    lv_obj_set_y(ui_Back, -4);
    lv_obj_set_align(ui_Back, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextBack = lv_label_create(ui_Back);
    lv_obj_set_width(ui_TextBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextBack, "返回");
    ui_object_set_themeable_style_property(ui_TextBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextBack, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WiFiWebPage, ui_event_WiFiWebPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AdvancedSetting, ui_event_AdvancedSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanSwitch, ui_event_FanSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RotationPlus, ui_event_RotationPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RotationMinus, ui_event_RotationMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);

}
