// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "../ui.h"

void ui_WeatherScreen_screen_init(void)
{
    ui_WeatherScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WeatherScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BG_Button);
    ui_object_set_themeable_style_property(ui_WeatherScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BG_Button);

    ui_WeatherBack = lv_btn_create(ui_WeatherScreen);
    lv_obj_set_width(ui_WeatherBack, 114);
    lv_obj_set_height(ui_WeatherBack, 24);
    lv_obj_set_x(ui_WeatherBack, 2);
    lv_obj_set_y(ui_WeatherBack, 104);
    lv_obj_set_align(ui_WeatherBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WeatherBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WeatherBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WeatherBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_WeatherBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextWeatherBack = lv_label_create(ui_WeatherBack);
    lv_obj_set_width(ui_TextWeatherBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWeatherBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextWeatherBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextWeatherBack, "主页");
    ui_object_set_themeable_style_property(ui_TextWeatherBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextWeatherBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextWeatherBack, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherSetting = lv_btn_create(ui_WeatherScreen);
    lv_obj_set_width(ui_WeatherSetting, 114);
    lv_obj_set_height(ui_WeatherSetting, 24);
    lv_obj_set_x(ui_WeatherSetting, -2);
    lv_obj_set_y(ui_WeatherSetting, 104);
    lv_obj_set_align(ui_WeatherSetting, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_WeatherSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WeatherSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WeatherSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_WeatherSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextWeatherSetting = lv_label_create(ui_WeatherSetting);
    lv_obj_set_width(ui_TextWeatherSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWeatherSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextWeatherSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextWeatherSetting, "设置");
    ui_object_set_themeable_style_property(ui_TextWeatherSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextWeatherSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextWeatherSetting, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDock = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_WeatherDock);
    lv_obj_set_width(ui_WeatherDock, 236);
    lv_obj_set_height(ui_WeatherDock, 104);
    lv_obj_set_x(ui_WeatherDock, 0);
    lv_obj_set_y(ui_WeatherDock, 2);
    lv_obj_set_align(ui_WeatherDock, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_WeatherDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WeatherDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_WeatherDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_ImageTemp = lv_img_create(ui_WeatherDock);
    lv_img_set_src(ui_ImageTemp, &ui_img_f7_thermometer_png);
    lv_obj_set_width(ui_ImageTemp, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_ImageTemp, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_ImageTemp, -12);
    lv_obj_set_y(ui_ImageTemp, -34);
    lv_obj_set_align(ui_ImageTemp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageTemp, 135);

    ui_ImageHumi = lv_img_create(ui_WeatherDock);
    lv_img_set_src(ui_ImageHumi, &ui_img_carbon_humidity_png);
    lv_obj_set_width(ui_ImageHumi, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_ImageHumi, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_ImageHumi, -13);
    lv_obj_set_y(ui_ImageHumi, -1);
    lv_obj_set_align(ui_ImageHumi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageHumi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageHumi, 160);

    ui_Humidity = lv_label_create(ui_WeatherDock);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 25);
    lv_obj_set_y(ui_Humidity, 0);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Humidity, "000%");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_ASCII32MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_WeatherDock);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 25);
    lv_obj_set_y(ui_Temperature, -33);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Temperature, "000℃");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_ASCII32MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherPanel = lv_obj_create(ui_WeatherDock);
    lv_obj_set_width(ui_WeatherPanel, 128);
    lv_obj_set_height(ui_WeatherPanel, 64);
    lv_obj_set_x(ui_WeatherPanel, -2);
    lv_obj_set_y(ui_WeatherPanel, 2);
    lv_obj_set_align(ui_WeatherPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_WeatherPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherICON = lv_img_create(ui_WeatherPanel);
    lv_img_set_src(ui_WeatherICON, &ui_img_999_png);
    lv_obj_set_width(ui_WeatherICON, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_WeatherICON, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_WeatherICON, -10);
    lv_obj_set_y(ui_WeatherICON, 0);
    lv_obj_set_align(ui_WeatherICON, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WeatherICON, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherICON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherICON, 225);

    ui_Week = lv_label_create(ui_WeatherPanel);
    lv_obj_set_width(ui_Week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Week, 10);
    lv_obj_set_y(ui_Week, 0);
    lv_obj_set_align(ui_Week, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Week, "错误");
    lv_obj_set_style_text_color(ui_Week, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Week, &ui_font_CHN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheatherCHN0Panel = lv_obj_create(ui_WeatherDock);
    lv_obj_set_width(ui_WheatherCHN0Panel, 232);
    lv_obj_set_height(ui_WheatherCHN0Panel, 34);
    lv_obj_set_x(ui_WheatherCHN0Panel, 0);
    lv_obj_set_y(ui_WheatherCHN0Panel, -2);
    lv_obj_set_align(ui_WheatherCHN0Panel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_WheatherCHN0Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheatherCHN0Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheatherCHN0Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheatherCHN0Panel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheatherCHN0Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherCHN = lv_label_create(ui_WheatherCHN0Panel);
    lv_obj_set_width(ui_WeatherCHN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherCHN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherCHN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherCHN, "错误");
    lv_obj_set_style_text_color(ui_WeatherCHN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherCHN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherCHN, &ui_font_CHN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeDock = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_TimeDock);
    lv_obj_set_width(ui_TimeDock, 236);
    lv_obj_set_height(ui_TimeDock, 56);
    lv_obj_set_x(ui_TimeDock, 0);
    lv_obj_set_y(ui_TimeDock, 16);
    lv_obj_set_align(ui_TimeDock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_TimeDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextWTime = lv_label_create(ui_TimeDock);
    lv_obj_set_width(ui_TextWTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextWTime, 0);
    lv_obj_set_y(ui_TextWTime, 3);
    lv_obj_set_align(ui_TextWTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextWTime, ":  :");
    ui_object_set_themeable_style_property(ui_TextWTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_TextWTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_TextWTime, &ui_font_ASCII56MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WHour = lv_label_create(ui_TimeDock);
    lv_obj_set_width(ui_WHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WHour, -84);
    lv_obj_set_y(ui_WHour, 3);
    lv_obj_set_align(ui_WHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WHour, "00");
    ui_object_set_themeable_style_property(ui_WHour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_WHour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_WHour, &ui_font_ASCII56MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WMinute = lv_label_create(ui_TimeDock);
    lv_obj_set_width(ui_WMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WMinute, 0);
    lv_obj_set_y(ui_WMinute, 3);
    lv_obj_set_align(ui_WMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WMinute, "00");
    ui_object_set_themeable_style_property(ui_WMinute, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_WMinute, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_WMinute, &ui_font_ASCII56MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WSecond = lv_label_create(ui_TimeDock);
    lv_obj_set_width(ui_WSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WSecond, 84);
    lv_obj_set_y(ui_WSecond, 3);
    lv_obj_set_align(ui_WSecond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WSecond, "00");
    ui_object_set_themeable_style_property(ui_WSecond, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text_Switch);
    ui_object_set_themeable_style_property(ui_WSecond, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text_Switch);
    lv_obj_set_style_text_font(ui_WSecond, &ui_font_ASCII56MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerDock = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_PowerDock);
    lv_obj_set_width(ui_PowerDock, 236);
    lv_obj_set_height(ui_PowerDock, 40);
    lv_obj_set_x(ui_PowerDock, 0);
    lv_obj_set_y(ui_PowerDock, 68);
    lv_obj_set_align(ui_PowerDock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PowerDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PowerDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_PowerDock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_TextWVoltage = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_TextWVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextWVoltage, -80);
    lv_obj_set_y(ui_TextWVoltage, 2);
    lv_obj_set_align(ui_TextWVoltage, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextWVoltage, "主电压");
    lv_obj_set_style_text_color(ui_TextWVoltage, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextWVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextWVoltage, &ui_font_CHN18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextWCurrent = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_TextWCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextWCurrent, 0);
    lv_obj_set_y(ui_TextWCurrent, 2);
    lv_obj_set_align(ui_TextWCurrent, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextWCurrent, "主电流");
    lv_obj_set_style_text_color(ui_TextWCurrent, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextWCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextWCurrent, &ui_font_CHN18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextPower1 = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_TextPower1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPower1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPower1, 80);
    lv_obj_set_y(ui_TextPower1, 2);
    lv_obj_set_align(ui_TextPower1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextPower1, "主功率");
    lv_obj_set_style_text_color(ui_TextPower1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPower1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPower1, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WVoltage = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_WVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WVoltage, -80);
    lv_obj_set_y(ui_WVoltage, 10);
    lv_obj_set_align(ui_WVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WVoltage, "00.00V");
    lv_obj_set_style_text_color(ui_WVoltage, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WVoltage, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WCurrent = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_WCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WCurrent, 0);
    lv_obj_set_y(ui_WCurrent, 10);
    lv_obj_set_align(ui_WCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WCurrent, "00.00A");
    lv_obj_set_style_text_color(ui_WCurrent, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WCurrent, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WPower = lv_label_create(ui_PowerDock);
    lv_obj_set_width(ui_WPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WPower, 80);
    lv_obj_set_y(ui_WPower, 10);
    lv_obj_set_align(ui_WPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WPower, "000.0W");
    lv_obj_set_style_text_color(ui_WPower, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WPower, &ui_font_ASCII20MONO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WeatherBack, ui_event_WeatherBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WeatherSetting, ui_event_WeatherSetting, LV_EVENT_ALL, NULL);

}
